name: Build and Deploy MyPortfolio

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      # This checks out your repository's code.

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
      # This sets up the .NET environment. Replace '7.0.x' with the version your project requires.

    - name: Restore dependencies
      run: dotnet restore ./MyPortfolio/MyPortfolio.csproj
      # This restores the project's dependencies.

    - name: Build
      run: dotnet build ./MyPortfolio/MyPortfolio.csproj --configuration Release
      # This builds the project in Release configuration.

    - name: Publish
      run: dotnet publish ./MyPortfolio/MyPortfolio.csproj -c Release -o out
      # This publishes the application to the 'out' directory.

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out
      # This deploys the application to GitHub Pages.
